apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name:  kube-prometheus-stack-cosmos.rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack  
    role: alert-rules    
    instance: kube-prometheus-stack
    heritage: Helm
    release: kube-prometheus-stack
spec:    
  groups:
  - name: cosmos.wallet-balance
    rules:
      - alert: CosmosWalletBalance 
        annotations:
          description: wallet has less than 1 token 
          summary: feed the meter
        expr: |-
          cosmos_wallet_balance{namespace="cosmos"}  < 1
        for: 10m
        labels:
          severity: warning
  - name: cosmos.stalled_node
    rules:
      - alert: CosmosStalledNode
        annotations:
          description: Node isn't consuming CPU
          summary: it's dead jim
        expr: |-
          rate(container_cpu_usage_seconds_total{container="node",namespace="cosmos"}[5m])<0.02
        for: 10m
        labels:
          severity: critical
      - alert: CosmosStalledHeight
        annotations:
          description: Height isn't going up
          summary: it's dead jim
        expr: |-
          rate(cometbft_consensus_height{namespace="cosmos"}[10m]) == 0
        for: 10m
        labels:
          severity: critical
  - name: cosmos.active-props
    rules:
      - alert: CosmosActiveProposalsNotVoted
        annotations:
          description: proposals not voted on
          summary: feed the meter
        expr: |-
          cosmos_validator_voting_proposals{namespace="cosmos"} >0
        for: 100m
        labels:
          severity: info
  - name: cosmos.upgrades
    rules:
      - alert: CosmosUpgrades
        annotations:
          description: chains upgrade
          summary: chain has upgrade coming up
        expr: |-
          cosmos_upgrade_plan{namespace="cosmos"} >0
        for: 10m
        labels:
          severity: info
      - alert: CosmosUpgradesSoon
        annotations:
          description: chains about to be upgrade <1000 blocks
          summary: chain about to upgrade
        expr: |-
          cosmos_upgrade_plan{namespace="cosmos"} >0 and cosmos_upgrade_plan{namespace="cosmos"} < 1000
        for: 10m
        labels:
          severity: warning
