apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name:  kube-prometheus-stack-cosmos.rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack  
    role: alert-rules    
    instance: kube-prometheus-stack
    heritage: Helm
    release: kube-prometheus-stack
spec:    
  groups:
  - name: cosmos.wallet-balance
    rules:
      - alert: CosmosWalletBalance 
        annotations:
          description: wallet has less than 1 token 
          summary: feed the meter
        expr: |-
          cosmos_wallet_balance{namespace="cosmos"}  < 1
        for: 10m
        labels:
          severity: warning
  - name: cosmos.stalled_node
    rules:
      - alert: CosmosStalledNode
        annotations:
          description: Node isn't consuming CPU
          summary: it's dead jim
        expr: |-
          rate(container_cpu_usage_seconds_total{container="node",namespace="cosmos"}[5m])<0.02
        for: 10m
        labels:
          severity: critical