---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cosmos-osmo-test-5
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/cosmos/osmo-test-5
  prune: true
  targetNamespace: cosmos
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
