---
- name: add Docker apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add Docker's APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable"
    filename: "docker"

- name: apt-update-container
  shell: |
    apt update
  changed_when: false

- name: Install container
  apt:
    name:
    - containerd.io
    state: latest
    update_cache: true

- name: containerD configure/setup
  shell: containerd config default > /etc/containerd/config.toml 
  changed_when: false

- name: configure container
  command: 'sudo sed -i "s/SystemdCgroup \= false/SystemdCgroup \= true/g" /etc/containerd/config.toml'
  changed_when: false

- name: containerd start
  systemd: 
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
  changed_when: false

- name: add Kubernetes apt-key
  command: 'curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg'
  changed_when: true
 # apt_key:   
  #curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
 #   url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
 #   state: present

- name: apt-add Kubernetes
  apt_repository:    
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
    state: present
    filename: 'kubernetes'

- name: apt-update-Kubernetes
  shell: |
    apt update
  changed_when: false

- name: Install Kube commands
  apt:
    name:
    - kubelet
    - kubeadm
    - kubectl
    state: latest
    update_cache: true
- name: apt-update-Kubernetes
  command: 'sudo apt-mark hold kubelet kubeadm kubectl'
  changed_when: false

- name: reboot and wait for reboot to complete
  reboot:
