apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  name: harpoon 
  namespace: cosmos
spec:
  chain:
    app:
      minGasPrice: "0.00125ukuji,0.00125factory/kujira1ltvwg69sw3c5z99c6rr08hal7v0kdzfxz07yj5/demo"
      overrides: |-
        # Set app.toml overrides here. Such as:
        index-events = ["tx.hash", "tx.height"]
        [rosetta]
        enable = false
        [wasm]
        query-contract-gas-limit = "10000000"
        query-gas-limit = "10000000"
    binary: kujirad
    chainID: harpoon-4
    config:
      seeds: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:11856"
      overrides: |-
        [tx_index]
        indexer = "kv"
    genesisURL: https://snapshots.polkachu.com/testnet-genesis/kujira/genesis.json
    network: testnet
    skipInvariants: true
    snapshotURL: https://snapshots.polkachu.com/testnet-snapshots/kujira/kujira_25398818.tar.lz4
    versions:
      - height: 0
        image: ghcr.io/pfc-developer/heighliner/kujira:v0.9.2
      - height: 22263500
        image: ghcr.io/pfc-developer/heighliner/kujira:v0.9.3-1
      - height: 25700000
        image: ghcr.io/pfc-developer/heighliner/kujira:v1.0.0    
      - height: 25927440
        image: ghcr.io/pfc-developer/heighliner/kujira:v1.0.1
        setHaltHeight: true   
  podTemplate:
    probes:
      strategy: None
    resources:
      requests:
        memory: 16Gi
    affinity:
      podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - harpoon
            topologyKey: "zone"
  replicas: 3 # TODO change to 1 to use less resources
  volumeClaimTemplate:
    resources:
      requests:
        storage: 200Gi
    storageClassName: ssd-persistent-block-store
    accessModes: [ "ReadWriteOnce" ]
  service:
    p2pTemplate:
      type: NodePort
#    rpcTemplate:
#      type: ClusterIP
  type: Sentry