apiVersion: v1
kind: Service
metadata:
  name: harpoon-horcrux
  namespace: cosmos
spec:
  selector:
    app: harpoon-horcrux
  clusterIP: None
  affinity:
        # place the horcrux in the same zone as the sentry
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - harpoon
            topologyKey: "zone"
        # don't put two horcruxs in the same zone
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - harpoon-horcrux
              topologyKey: "zone"
  # Prometheus port
  ports:
  - protocol: TCP
    port: 26660
    targetPort: 26660
  