apiVersion: v1
stringData:
    ADDRESS: ENC[AES256_GCM,data:u1Vs/K2gRhn/fQIGEQ2drTk3IsWkqdnQFDn8xVvHY2Jd0jA4MrEVW6d+sqUG,iv:fSDF4+7oNiW8+6Q+GtrmUnUnxHABP7yrv2NnD81wuvM=,tag:eAq5I1FxReoyoKgYnOr9zQ==,type:str]
    VALIDATOR: ENC[AES256_GCM,data:H/WXuK6qvbpt33pv2qt9zIMHG8AbnBsGfcnd0TOKRTne/AycVVyCdJnaWP/nWxQE3wk/fw==,iv:BBaVqbk9NLJsM4b2JhXNW7IMpo4u4epPYUd42Zagi0o=,tag:Gg4DfsVnWaIJ9tHqvYX+VQ==,type:str]
    SEEDPHRASE: ENC[AES256_GCM,data:1Kg3hpMx4zrH1alPzPTIYjV1YYB69/9SDvemdH9f4Kx7QxbyvqBaXkVJTe5Daxih1mFt/tNwKHLUUD7ZYOR3h6SLe7CnDa81pwj485cYBq2QF/XN8LApue+BjyM4tbW1bugw4eIqRjYtAoAs8mn1HzFGD16n6+b4k/7dNaeJ3SOnYIXsiMwAHbTD1VjAuw6yhtJqBgLrcD87EkBB,iv:qDt+3o5UK8nNPY5qlkQTPuQFE8cnUPokf/Z59sx6AwM=,tag:2k/vuy0dGJid8YEVWjaWBA==,type:str]
kind: Secret
metadata:
    name: harpoon-price-feeder-secrets
    namespace: cosmos
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-27T18:44:17Z"
    mac: ENC[AES256_GCM,data:GOF8nV6QxA58JvhYPbA5RoPo1NxFETuMzG9/yi00AOdHmB6LMx7hK4LV7ZfFU0012WJsEoXfeEqz8kx9PdvB8BKOFvD8r/RfJUO+aNYklVtRTvO4nEl+ps01/X1xAHqc9KvPq6l//uFEDZdE7UJFHBNU72m79j7NgDFMFplL7ec=,iv:PlyWfplDxeAzvWL+Jm1Ys7p0/n+GD6wpOaoM/999ruw=,tag:VXwaHm/kOA0rwlGe9dos0w==,type:str]
    pgp:
        - created_at: "2023-09-27T18:44:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYj1NN/0GA4USAQdAV19ytdEMnfQRoVRZTmFgNBPIxm3uuJE7/vQlq8cXNxMw
            CqoO0G0vDur1oVmlhHLfUiS79aU+bv8vAsJA7s9v777lw/E2PDJIte1DhQi6xDcn
            0l4B34fCQN3YPwreFeLDbkZLQAte61YhmeVn4Tb3orPSJii4/gSvVC3NpdUF8vYg
            ENQmhDi/Bp662JPKLuP7FicaZ1RitZtbuYZGtnjJNJImxKEItmz+uffrFVNv7a5G
            =oJeu
            -----END PGP MESSAGE-----
          fp: 4C653A7AD53BC071B149AC6F05C9A59CE6F61D40
        - created_at: "2023-09-27T18:44:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlnT2alMWtDoSAQdAlHJTf9wDJC3gL1JB3jj4R5BPpFf6Ut4dY+x6AMZ/qUww
            9ZqDEiN6FsTSu+BtFkMTashzeIUCkBoqG7NyT54y2ckPjVUaHHSx+oAFVT7u+82W
            0l4Br/Vq7+rJ6piUuPXiKEtVAFQjOoS1x4TKzQNQOFJPo/lFxf+jq+SZA1zxJMdn
            QsYDKpu7tpzlIRXgozDLi+a/i63kspYtDTX6l8vb2blIT3tzkmTFYV8X4j48u2Mk
            =5c4E
            -----END PGP MESSAGE-----
          fp: 72C2A2A23FD55033E9FACA100A4AEEEFD51A640E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
