# signers
apiVersion: v1
stringData:
    SHARD: ENC[AES256_GCM,data:rPXp//x3p6RY+S0bSG7Zj7oMfYJplUDJY577dimuRyOQI5zFJtAnoPg3WIFg0auefnUFlRbmhNteDFLiqpAg1OwzHMzqGT+cma3kg4l6fv3MPaPdlckqjVvLzdDDfZItDexFsiffN9lOZuYskPCfnYsEbPKxHu5iy+bE3XLKeuV1Cw==,iv:+FtTeRYKbRd6X8jChWG6l5bhYe402p6dBRbr2P08t5M=,tag:mAsNYqzg0e6fhM8A6FcNBg==,type:str]
kind: Secret
metadata:
    name: harpoon-shard-1
    namespace: cosmos
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-27T22:20:46Z"
    mac: ENC[AES256_GCM,data:Z8iptfUITDbuTTxQHY2U0EYoyWc8qzVBmc53evYBsOJxvOkNezCyXfSSTGSp4+QJnjn6ZTkTJCqafPfpajNWMkub/vfSZROBQR+WOxTvhYp2nsWv0X2JQIxDrFZ7gJ3XWCDwiFRZSSuuz1C+VUTp+K5y552hrcXHiAviTgA2XS0=,iv:lm1CDmba/fICQ3gxJIeERuloInQBUzl68nUua8AvDlI=,tag:zClChf2w5aLBwYDHF7zXlQ==,type:str]
    pgp:
        - created_at: "2023-09-27T22:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYj1NN/0GA4USAQdABaSm7j1Ms7RWBI6jPp2NOY21FXWVaatTTFMK9Ml/8hcw
            o6pe9DwxfnxSGu9/7IUtXn70KE6viI3Jh6xdhwmLiqYTHJVbjfzgAvY7bPpjt+6g
            0l4Bbl2lXE8/uPzvcqlqC51v0DV+7AmlikKQhPu9q8whysi8y1owYHNIilVHig2R
            t476VDIneFc/Ac3xzNlrbF4fnkdGoWcrVE745vScCIek7XgzDIuf70ba5w9+idkY
            =ey3U
            -----END PGP MESSAGE-----
          fp: 4C653A7AD53BC071B149AC6F05C9A59CE6F61D40
        - created_at: "2023-09-27T22:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlnT2alMWtDoSAQdAc1wsZ8aa76g7t2M0iO59Eb09Wlm+3ejzQcvWNxzkEBQw
            w8d+phJlGcu17zmE3PgGtq46A1LzZTDvgHzzK8tHnG56VLrbWrnGLy214MBxYtK1
            0l4Bb/mkeQhGkIugLWMnpfexkq2jKU1omkHZRLTPhdRPh4op5x0Hd5Uln1l+3JZ7
            P5gxvOw4iH7cseTWJSTuD0OphC123tRGIjq2Z/4pYM5QJkh0OcILUsd0JJIwiCMO
            =TUei
            -----END PGP MESSAGE-----
          fp: 72C2A2A23FD55033E9FACA100A4AEEEFD51A640E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
stringData:
    SHARD: ENC[AES256_GCM,data:yLzT9XVWrNmKb/N44Kp39sTOHWfcFs9HDMqplXHYPc9NWFn3ziQXohEs7h/nH48iTVyyOwsOZLTgE7cMzSngHduWzAXmKOdor4+4LrkBbOiElLPgwps9Lf75GXamWGMviREDBn20WO+ucPg6n2+QbNbMjbrzV9CzclbQ4UqElPylyA==,iv:eAVk+Oe5yFqCEkvMkkFgh4/3u/QcEGDfNBuVYdBegaM=,tag:gIjw6iBhQZ79BuJsUqGm4g==,type:str]
kind: Secret
metadata:
    name: harpoon-shard-2
    namespace: cosmos
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-27T22:20:46Z"
    mac: ENC[AES256_GCM,data:Z8iptfUITDbuTTxQHY2U0EYoyWc8qzVBmc53evYBsOJxvOkNezCyXfSSTGSp4+QJnjn6ZTkTJCqafPfpajNWMkub/vfSZROBQR+WOxTvhYp2nsWv0X2JQIxDrFZ7gJ3XWCDwiFRZSSuuz1C+VUTp+K5y552hrcXHiAviTgA2XS0=,iv:lm1CDmba/fICQ3gxJIeERuloInQBUzl68nUua8AvDlI=,tag:zClChf2w5aLBwYDHF7zXlQ==,type:str]
    pgp:
        - created_at: "2023-09-27T22:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYj1NN/0GA4USAQdABaSm7j1Ms7RWBI6jPp2NOY21FXWVaatTTFMK9Ml/8hcw
            o6pe9DwxfnxSGu9/7IUtXn70KE6viI3Jh6xdhwmLiqYTHJVbjfzgAvY7bPpjt+6g
            0l4Bbl2lXE8/uPzvcqlqC51v0DV+7AmlikKQhPu9q8whysi8y1owYHNIilVHig2R
            t476VDIneFc/Ac3xzNlrbF4fnkdGoWcrVE745vScCIek7XgzDIuf70ba5w9+idkY
            =ey3U
            -----END PGP MESSAGE-----
          fp: 4C653A7AD53BC071B149AC6F05C9A59CE6F61D40
        - created_at: "2023-09-27T22:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlnT2alMWtDoSAQdAc1wsZ8aa76g7t2M0iO59Eb09Wlm+3ejzQcvWNxzkEBQw
            w8d+phJlGcu17zmE3PgGtq46A1LzZTDvgHzzK8tHnG56VLrbWrnGLy214MBxYtK1
            0l4Bb/mkeQhGkIugLWMnpfexkq2jKU1omkHZRLTPhdRPh4op5x0Hd5Uln1l+3JZ7
            P5gxvOw4iH7cseTWJSTuD0OphC123tRGIjq2Z/4pYM5QJkh0OcILUsd0JJIwiCMO
            =TUei
            -----END PGP MESSAGE-----
          fp: 72C2A2A23FD55033E9FACA100A4AEEEFD51A640E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
stringData:
    SHARD: ENC[AES256_GCM,data:PUGmeaa2qijzq24U06A9f18PDqXUk66DhyzlsgRRvGZ3Vb46q2YVFrUi8R8fP0wPqd/beWkiujk0lp38o/hGglbeoWNig5xBUALUQ1pL5ecdd1zGQmTV4Pcu/hIDXgVomqn+PYREQpner4PKsW8G3qhyXptHkZpAwKDW02r/k76Jzg==,iv:5rg11eurx2iqygMpNrmGHkiZot1/tiMWIclXXM4eA8M=,tag:Kkl8rBWCDvMmc5bg+VJxIw==,type:str]
kind: Secret
metadata:
    name: harpoon-shard-3
    namespace: cosmos
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-27T22:20:46Z"
    mac: ENC[AES256_GCM,data:Z8iptfUITDbuTTxQHY2U0EYoyWc8qzVBmc53evYBsOJxvOkNezCyXfSSTGSp4+QJnjn6ZTkTJCqafPfpajNWMkub/vfSZROBQR+WOxTvhYp2nsWv0X2JQIxDrFZ7gJ3XWCDwiFRZSSuuz1C+VUTp+K5y552hrcXHiAviTgA2XS0=,iv:lm1CDmba/fICQ3gxJIeERuloInQBUzl68nUua8AvDlI=,tag:zClChf2w5aLBwYDHF7zXlQ==,type:str]
    pgp:
        - created_at: "2023-09-27T22:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DYj1NN/0GA4USAQdABaSm7j1Ms7RWBI6jPp2NOY21FXWVaatTTFMK9Ml/8hcw
            o6pe9DwxfnxSGu9/7IUtXn70KE6viI3Jh6xdhwmLiqYTHJVbjfzgAvY7bPpjt+6g
            0l4Bbl2lXE8/uPzvcqlqC51v0DV+7AmlikKQhPu9q8whysi8y1owYHNIilVHig2R
            t476VDIneFc/Ac3xzNlrbF4fnkdGoWcrVE745vScCIek7XgzDIuf70ba5w9+idkY
            =ey3U
            -----END PGP MESSAGE-----
          fp: 4C653A7AD53BC071B149AC6F05C9A59CE6F61D40
        - created_at: "2023-09-27T22:20:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DlnT2alMWtDoSAQdAc1wsZ8aa76g7t2M0iO59Eb09Wlm+3ejzQcvWNxzkEBQw
            w8d+phJlGcu17zmE3PgGtq46A1LzZTDvgHzzK8tHnG56VLrbWrnGLy214MBxYtK1
            0l4Bb/mkeQhGkIugLWMnpfexkq2jKU1omkHZRLTPhdRPh4op5x0Hd5Uln1l+3JZ7
            P5gxvOw4iH7cseTWJSTuD0OphC123tRGIjq2Z/4pYM5QJkh0OcILUsd0JJIwiCMO
            =TUei
            -----END PGP MESSAGE-----
          fp: 72C2A2A23FD55033E9FACA100A4AEEEFD51A640E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
