apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- infrastructure.yaml
#- rook-ceph.yaml
#- ingress.yaml
- cosmos.yaml
#- apps.yaml
#- monitoring.yaml
#- github-private.yaml