apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/apps/podinfo
  prune: true
#  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
