apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
 # targetNamespace: rook-ceph
  sourceRef:
    kind: GitRepository
    name: gh-private
