#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mainnet
  namespace: cosmos-mainnet
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: mainnet
  sourceRef:
    kind: GitRepository
    name: mainnet
