#
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cosmos-monitor-mainnet
  namespace: cosmos
  labels:
    k8s-apps: http
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      cosmos.strange.love/network: mainnet

  podMetricsEndpoints:
  - port: prometheus
    interval: 15s