# http auth created via htpasswd -c auth username
apiVersion: v1
stringData:
    #ENC[AES256_GCM,data:UlSKuseUAt1ZgY3Qc3PTN9yPOSlca1YSXyuACY/3GV8pL0rn0Fui2S1akUBWYtNCyY0C4G1WysbacaIzlK7rzxUkYPufzmdcPt4dfrkpUcbm5cVhsQUt6Z8Sxfg=,iv:o6qg6P4whOh11TbrkO8yNhNALpZet0KwXLDrO9lOdF0=,tag:cdQnJbAF39vs8gYPUsr5Iw==,type:comment]
    slack: ENC[AES256_GCM,data:FXJZevGkzzubNAqklx9/mfcYlsDjBRfVpeXEqtKq0ppQjpyhQ9mwyFTN/XIh0wh1aqLdMr4F7IerzEtIU7Rm4RmboHECo8/9qWpEN3IYqk/6,iv:Zlmy9PaQ+5Yb0yUV0jQQau8u/1sWHYG8lXTnSG1xFCA=,tag:wLFyO0yjoPJOJ1xsEFccoQ==,type:str]
kind: Secret
metadata:
    name: alertmanager-secrets
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-31T16:47:29Z"
    mac: ENC[AES256_GCM,data:X00JI1NK8K1b97f/NRoxzQN2ew8JxM73asSChVKYYaaRED8fXM1nQ1bLFJ/qu72Hf/8dgChW07FVKtxOKg+zaXDWSRIrRlek2PJZpSKJ/WeLY5AA2/B9TwChptMBx9/VODKm8hVBQz5ywnEwy/gzYQ44b2UhTMVUnn0mD8PiFkw=,iv:StE8jAPUk4WFL+6d9mVHUr/KUPE/BJd4juxLGmTF7uQ=,tag:TkPrlzFvasi433Md8R38wQ==,type:str]
    pgp:
        - created_at: "2023-10-31T16:47:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYj1NN/0GA4USAQdAIIVvsyMKe9lloe0SD8GTiZEJaIQXogzooEy8CsiDgAgw
            07eH6s5o+RbqMwr+tA1MhhuJliWabgyM9TOArgdKLKWRfOKY62GNiJXV21z3eYrQ
            0l4BGZCu+RXx8uCZ1QdBq3zPefpN+5vFCTqxXnW2BVNUl+eV4M40oORWztu5uo2f
            AYZZwsmTomwBxtf042nzQLsEwl42H2yOoU+qGLMb/7t4qbxbwHqrJwTS+7NJLMPR
            =Zx3Q
            -----END PGP MESSAGE-----
          fp: 4C653A7AD53BC071B149AC6F05C9A59CE6F61D40
        - created_at: "2023-10-31T16:47:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DlnT2alMWtDoSAQdANDWMMsgFRok5oMHt0u1lA/WfOoE6t5+xIaMlHSclZHAw
            MgNXD53n5Qyz8dr+yCiQg0rgwVFSj0sUYr3D1F2d0mXwR4PimwVMDNDgGfrITXX5
            0l4BsaA2ZvPU6NEKM+CTz1b0S/fP/awHIo69z8+uIrzlr8Qouxv3xfy6UrP/W4tN
            yhUaski7HoN21npnbv5DyJ5fNEI3b4P66I2WxjDomfw3h1l0sB53zVjEnzgt4CEE
            =9yRe
            -----END PGP MESSAGE-----
          fp: 72C2A2A23FD55033E9FACA100A4AEEEFD51A640E
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
