apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: kube-prometheus-stack-alertmanagerconfig
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: alertmanagerconfig
    alertmanagerConfig: slack
spec:
  route:
    groupBy: ['job']
    receiver: slack_router
    groupWait: 0s
    groupInterval: 5m
    repeatInterval: 2h      
  receivers:
    - name: slack_router
      slackConfigs:
        - apiURL:
            name: alertmanager-secrets
            key: slack
          channel: 'alerts'