---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-operator
  namespace: strimzi-operator-system
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.47.0"
      sourceRef:
        kind: HelmRepository
        name: oci-operator-strimzi
        namespace: strimzi-operator-system
      interval: 1m
  values:
    watchAnyNamespace: true
    dashboards:
      enabled: true 
      namespace: monitoring