{
 "title": "Relayer Hermes - polkachu",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(acknowledgment_packets_confirmed_total,instance)"
    }
   },
   {
    "name": "source_chain",
    "label": "Source Chain",
    "query": {
     "query": "label_values(acknowledgment_packets_confirmed_total{instance=\"$instance\"},src_chain)"
    }
   },
   {
    "name": "source_channel",
    "label": "Source Channel",
    "query": {
     "query": "label_values(acknowledgment_packets_confirmed_total{instance=\"$instance\", src_chain=\"$source_chain\"},src_channel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$source_chain $source_channel  Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ibc_acknowledgment_packets{instance=\"$instance\", src_chain=\"$source_chain\", src_channel=\"$source_channel\"}[10m])",
     "legendFormat": "Acknowledgement"
    },
    {
     "expr": "rate(ibc_receive_packets{instance=\"$instance\", src_chain=\"$source_chain\", src_channel=\"$source_channel\"}[10m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(ibc_timeout_packets{instance=\"$instance\", src_chain=\"$source_chain\", src_channel=\"$source_channel\"}[10m])",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Overall Workers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workers{instance=\"$instance\"}\n"
    }
   ]
  },
  {
   "title": "Overall Acknowledgements",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(acknowledgment_packets_confirmed_total{instance=\"$instance\"}[10m])",
     "legendFormat": "{{ src_chain }}: {{ src_channel }}"
    }
   ]
  },
  {
   "title": "Overall Receives",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(receive_packets_confirmed_total{instance=\"$instance\"}[10m])",
     "legendFormat": "{{ src_chain }}: {{ src_channel }}"
    }
   ]
  },
  {
   "title": "Overall Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(timeout_packets_confirmed_total{instance=\"$instance\"}[10m])",
     "legendFormat": "{{ src_chain }}: {{ src_channel }}"
    }
   ]
  }
 ]
}