{
 "title": "Hermes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Hermes Grafana Dashboard\n\nhttp://hermes.informal.systems/documentation/telemetry/operators.html to learn more about the metrics."
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 }, "options": { "content": "# Is hermes active ?" } },
  {
   "title": "Wallet balances",
   "type": "barchart",
   "description": "Indicates if you have enough funds on your wallet. Hermes can not relay without spending gas. Thus, it is important to set alarms which monitor the gas.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "wallet_balance{namespace=\"pfc\"}",
     "legendFormat": "{{chain}}: {{account}} ({{instance}})"
    }
   ]
  },
  {
   "title": "client_updates_submitted over 1 minute",
   "type": "timeseries",
   "description": "Indicates if clients are getting updated.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "delta(client_updates_submitted_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{src_chain}} -> {{dst_chain}}:{{client}} ({{instance}})"
    }
   ]
  },
  {
   "title": "messages_submitted over 1 minute",
   "type": "timeseries",
   "description": "Indicates if Hermes is submitting messages to a specific chain ",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "delta(messages_submitted_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "Gas variation over 1 minute",
   "type": "timeseries",
   "description": "Indicates if you are spending gas and how much you are spending.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "delta(wallet_balance{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{chain}}: {{account}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Current number of workers",
   "type": "timeseries",
   "description": "This panel indicates which type of workers are active for every instance.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "workers{namespace=\"pfc\"}",
     "legendFormat": "{{instance}}:{{type}}"
    }
   ]
  },
  {
   "title": "95th quantile of tx_latency_confirmed rate over 5 minutes",
   "type": "timeseries",
   "description": "Indicates the latency rate for all transactions confirmed by each chain.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, chain) (rate(tx_latency_confirmed_bucket[5m])))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "# Are transaction successful ?\n"
   }
  },
  {
   "title": "Oldest pending packets",
   "type": "table",
   "description": "Represents the sequence number and the date of the oldest pending packet. Use this metric to identify stuck packets.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "backlog_oldest_sequence{namespace=\"pfc\"}",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    },
    {
     "expr": "backlog_oldest_timestamp{namespace=\"pfc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending packet per path",
   "type": "timeseries",
   "description": "Indicates how many packets are being processed by Hermes. If this value stays constantly more than 0, it could mean that a packet is stuck.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "backlog_size{namespace=\"pfc\"}",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "receive_packets_confirmed over 1 minute",
   "type": "timeseries",
   "description": "Indicates how many `receive_packets` were processed by Hermes. It can be used with `send_packet_events` as every `send_packet_event` should trigger the processing of a `receive_packet`.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "delta(receive_packets_confirmed_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}} ({{instance}})"
    }
   ]
  },
  {
   "title": "timeout_packets_confirmed over 1 minute",
   "type": "timeseries",
   "description": "Indicates how many `timeout_packets` were processed by the relayer. It can be used with `timeout_packet_events` as every `timeout_event` should be processed by Hermes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "delta(timeout_packets_confirmed_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}} ({{instance}})"
    }
   ]
  },
  {
   "title": "acknowledgment_packets_confirmed over 1 minute",
   "type": "timeseries",
   "description": "Indicates how many acknowledgements were processed by the relayer. It can be used with `acknowledgment_events` as every event should be processed by Hermes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "delta(acknowledgment_packets_confirmed_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}} ({{instance}})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "# What is the overall IBC status of each network?\r\n\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "send_packets_events over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `send_packet_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "delta(send_packet_events_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "acknowledgement_events over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `acknowledgement_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "delta(acknowledgement_events_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "timeout_events over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `timeout_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "delta(timeout_events_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "ws_events received over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `event` observed via the websocket subcription.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "delta(ws_events_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "ws_reconnect over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of times Hermes reconnected to the websocket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "expr": "delta(ws_reconnect_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "RPC queries sent over 1 minute",
   "type": "timeseries",
   "description": "Indicate the number of queries per instance and chain.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "sum(delta(queries_total{namespace=\"pfc\"}[1m])) by(instance,chain)",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "options": {
    "content": "# How efficient and how secure is the IBC status on each network ?\n\n"
   }
  },
  {
   "title": "cleared_acknowledgment_events over 1 minute",
   "type": "timeseries",
   "description": "Cleared `acknowledgment_events` rate per path. It is an indication that IBC packet relaying may be unsuccessful and that Hermes periodically finds packets to clear (i.e., unblock).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "delta(cleared_acknowledgment_events_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "cleared_send_packet_events over 1 minute",
   "type": "timeseries",
   "description": "Cleared `send_packet_events` rate per path. It is an indication that IBC packet relaying may be unsuccessful and that Hermes periodically finds packets to clear (i.e., unblock).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "delta(cleared_send_packet_events_total{namespace=\"pfc\"}[1m])",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    }
   ]
  },
  {
   "title": "95th quantile of tx_latency_submitted rate over 5 minutes",
   "type": "timeseries",
   "description": "Indicates the latency rate for all transactions submitted to each chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, chain, instance) (rate(tx_latency_submitted_bucket[5m])))",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "queries_cache_hits over 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum by(chain, instance) (delta(queries_cache_hits_total{namespace=\"pfc\"}[1m]))",
     "legendFormat": "{{instance}}:{{chain}}"
    }
   ]
  },
  {
   "title": "tx_latency_submitted histogram ibc-0",
   "type": "bargauge",
   "description": "Indicates the latency rate for all transactions submitted from ibc-0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tx_latency_submitted_bucket{chain=\"ibc-0\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tx_latency_confirmed_bucket histogram ibc-0",
   "type": "bargauge",
   "description": "Indicates the latency rate for all transactions confirmed from ibc-0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tx_latency_confirmed_bucket{chain=\"ibc-0\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "client_misbehaviours_submitted over 5 minutes",
   "type": "timeseries",
   "description": "If `misbehaviour = true` then hermes will detect misbehaviours from clients and stop relaying to this client if one is detected. It is possible to set an alarm on this. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "delta(client_misbehaviours_submitted_total[5m])",
     "legendFormat": "{{src_chain}}-{{dst_chain}}:{{client}} ({{instance}})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 104 }, "options": { "content": "# Extra" } }
 ]
}