apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-metallb-operator
  namespace: operators
spec:
  channel: beta
  name: metallb-operator
  source: operatorhubio-catalog
  sourceNamespace: olm