# manifests/infrastructure/external-dns/external-dns.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m0s
  url:  https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace:  metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      #version: ">=v1.13.0 <1.14.0"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace:  metallb-system
      interval: 1m
  values:
    loadbalancerClass: "metal"
   