apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  name: neutron
  namespace: cosmos
  annotations:
    prometheus.io/port: "prometheus"
    prometheus.io/scrape: "true"
spec:
  chain:
    app:
      minGasPrice: "0.0053untrn"
      #haltHeight: 16200000
      overrides: |-
        # Set app.toml overrides here. Such as:
        index-events = ["tx.hash", "tx.height"]
        pruning-keep-recent = "7203"
        pruning-keep-every = "1000"
        pruning-interval = "11"
        [rosetta]
        enable = false
        [wasm]
        query-contract-gas-limit = "10000000"
        query_gas_limit = "10000000"
        query-gas-limit = "10000000"
        memory_cache_size = 400 

    binary: neutrond
    chainID: neutron-1
    config:
      seeds: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:19156"

      #maxInboundPeers: 20
      #maxOutboundPeers: 70
      overrides: |-
        [tx_index]
        indexer = "kv"
    genesisURL:  https://snapshots.polkachu.com/genesis/neutron/genesis.json
    network: mainnet
    skipInvariants: true
    snapshotURL: https://snapshots.polkachu.com/snapshots/neutron/neutron_19274186.tar.lz4
    versions:
      - height: 0
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v3.0.2
      - height: 10525000
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v3.0.5
      - height: 11298600
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v3.0.6
      - height: 12255555
      #emergency upgrade.
#       image: ghcr.io/pfc-developer/heighliner/neutron:v4.0.1
        image: ghcr.io/pfc-developer/heighliner/neutron:v4.1.0
      - height: 13261400
        image: ghcr.io/pfc-developer/heighliner/neutron:v4.2.0
      - height: 13711950
        image: ghcr.io/pfc-developer/heighliner/neutron:v4.2.3
      - height: 13711951
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v4.2.4
      - height: 16738000
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v5.0.1
      - height: 17177900
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v5.0.2
      - height: 18015000
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v5.0.4
      - height: 18125000
        image: ghcr.io/pfc-developer/heighliner/neutron:v5.0.5
      - height: 18906878
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v5.0.6
       # setHaltHeight: true
      - height: 19660000
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v5.0.7
      - height: 19947000
        image: ghcr.io/strangelove-ventures/heighliner/neutron:v5.1.0

  podTemplate:
    resources:
      requests:
        memory: 16Gi
        cpu: 6
    affinity:
      nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: provider
                operator: In
                values:
                - lsw
                - ovh    
      podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - neutron
            topologyKey: "zone"  
  replicas: 2 # TODO change to 1 to use less resources
  volumeClaimTemplate:
    resources:
      requests:
        storage: 350Gi
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: ssd-persistent-block-store
  service:
    maxP2PExternalAddresses: 2  
    p2pTemplate:
      externalTrafficPolicy: Cluster
      type: NodePort
