---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster.yaml
- replicated-x3-block-store.yaml
- ssd-impermanent-block-store.yaml
- ssd-block-store.yaml
- sentry-block-store.yaml
- storage-class-workaround.yaml