# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: rpc.cosmoshub.yieldpay.finance
    nginx.ingress.kubernetes.io/enable-cors: "true"

  labels:
    app.kubernetes.io/name: cosmoshub-rpc
    app.kubernetes.io/version: 1.0.0
  name: cosmoshub-rpc
  namespace: cosmos
spec:
  ingressClassName: nginx
  rules:
  - host: rpc.cosmoshub.yieldpay.finance
    http:
      paths:
      - backend:
          service:
            name: cosmoshub-rpc
            port:
              number: 26657
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - rpc.cosmoshub.yieldpay.finance
    secretName: cosmoshub-rpc-tls-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    external-dns.alpha.kubernetes.io/hostname: grpc.cosmoshub.yieldpay.finance
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: cosmoshub-grpc
  namespace: cosmos
spec:
  ingressClassName: nginx
  rules:
  - host: grpc.cosmoshub.yieldpay.finance
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cosmoshub-rpc
            port:
              number: 9090
  tls:
  - hosts:
    - grpc.cosmoshub.yieldpay.finance
    secretName: cosmoshub-grpc-tls-secret

   