apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  name: noble
  namespace: cosmos
  annotations:
    prometheus.io/port: "prometheus"
    prometheus.io/scrape: "true"
spec:
  chain:
    app:
      minGasPrice: "0.000uusdc"
      pruning: 
        interval: 137
        strategy: custom 
        keepRecent: 4889
      overrides: |-
        # Set app.toml overrides here. Such as:
        index-events = ["tx.hash", "tx.height"]
        [rosetta]
        enable = false

    binary: nobled
    chainID: noble-1
    config:
      seeds: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:21556"
      maxOutboundPeers: 70
    genesisURL: https://snapshots.polkachu.com/genesis/noble/genesis.json
    network: mainnet
    skipInvariants: true
    snapshotURL: https://snapshots.polkachu.com/snapshots/noble/noble_22264357.tar.lz4
    versions:
      - height: 0
        image: ghcr.io/pfc-developer/heighliner/noble:v4.0.3
      - height: 5797500
        image: ghcr.io/strangelove-ventures/heighliner/noble:v4.1.1
      - height: 6022000
        image: ghcr.io/strangelove-ventures/heighliner/noble:v4.1.3
      - height: 7947000
        image: ghcr.io/strangelove-ventures/heighliner/noble:v5.0.0        
      - height: 11148012
      # actually 7947000
        image: ghcr.io/strangelove-ventures/heighliner/noble:v6.0.0                
      - height: 12240000
        image: ghcr.io/strangelove-ventures/heighliner/noble:v7.0.0
      - height: 15374999
        image: ghcr.io/strangelove-ventures/heighliner/noble:v8.0.4
        setHaltHeight: true
  podTemplate:
    resources:
      requests:
        cpu: 2
        memory: 16Gi
    affinity:
      nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: provider
                operator: In
                values:
                - lsw
                - ovh                   
      podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - noble
            topologyKey: "zone"        
  replicas: 2 # TODO change to 1 to use less resources
  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Gi
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: ssd-persistent-block-store
  service:
    p2pTemplate:
      externalTrafficPolicy: Cluster
      type: NodePort
