apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cosmos-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infrastructure/cosmos-operator/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
