#
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- rook-ceph.yaml
- cosmos-operator.yaml
- ingress.yaml
- monitoring.yaml
- private-repo.yaml
- storage/
#- metallb.yaml