apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infrastructure/strimzi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: strimzi-operator-system
