apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: valkey
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infrastructure/valkey
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: valkey-operator-system
