---
- hosts: ies
  gather_facts: no
  become: true
  tasks:

    # setup mongo + injective
    - name: setting up mongo+inj
      shell: |
       cd /opt/injective-chain-releases/docker
       docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --remove-orphans mongo injective-core
      