apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-persistent-block-store
parameters:
  is-default-class: "true"
  storage: "lvm"
  volgroup: "VG-topolvm"
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer