apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-persistent-block-store
#  annotations:  
#    storageclass.kubernetes.io/is-default-class: "true"
parameters:  
  storage: "lvm"
  volgroup: "VG-topolvm"
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-persistent-lvm
parameters:  
  storage: "lvm"
  volgroup: "VG-topolvm"
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
  annotations:  
    storageclass.kubernetes.io/is-default-class: "true"

parameters:
  storage: "lvm"
  volgroup: "VG-topolvm"
provisioner: local.csi.openebs.io