apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name:  ssd-persistent-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"  
driver: local.csi.openebs.io
deletionPolicy: Delete
parameters:  
  storage: "lvm"
  volgroup: "VG-topolvm"