apiVersion: v1
kind: Service
metadata:
  name: pryzm
  namespace: pfc
spec:
  selector:
    app.kubernetes.io/name: pryzm
  clusterIP: None
  ports:
  - protocol: TCP
    port: 1234
    targetPort: 1234
  - protocol: TCP
    port: 26657
    targetPort: 26657
  - protocol: TCP
    port: 1317
    targetPort: 1317
  - protocol: TCP
    port: 9091
    targetPort: 9091
