#
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gh-private
  namespace: flux-system
spec:
  interval: 1m10s
  ref:
    branch: main
  url: ssh://git@github.com/PFC-Validator/PFC-Cluster-Private.git
  secretRef:
    name: private-repo